spring:
  application:
    name: springai-mcp

  ai:
    #    ollama:
    #      base-url: http://localhost:7869
    #      chat:
    #        options:
    #          model: Qwen3
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          temperature: 0.7
          #model: gpt-5
          model: gpt-4.1-nano
    mcp:
      client:
        stdio:
          # Following are two possible ways to configure the MCP client to use the Brave Search server.
          # When using servers-configuration option, don't place key placeholder in the configuration file, instead use environment variable to pass the key to the program.
          # Option 1: Use servers-configuration to specify the configuration file for the MCP client.
          servers-configuration: "classpath:mcp-servers-config.json"

          # Option 2: Use connections to specify the Brave Search server connection details directly in the application.yaml file.
#          connections:
#            brave-search:
#              env:
#                BRAVE_API_KEY: ${BRAVE_API_KEY}
#              command: npx  # This would require installation of NPX/NPM/NODE on the host machine where this program is running
#              args: -y,@modelcontextprotocol/server-brave-search

# Following does not work.
#    mcp:
#      client:
#        streamable-http:
#          connections:
#            brave-search:
#              url: https://api.brave.com
#              endpoint: /mcp
#              headers:
#                BRAVE_API_KEY: ${BRAVE_API_KEY}

server:
  port: 8081

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # Set to 1.0 for local debugging
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
  metrics:
    distribution:
      percentiles-histogram:
        gen.ai.client.token.usage: true
        spring.ai.chat.client: true

logging:
  level:
    io.modelcontextprotocol: DEBUG
    org.springframework.web.reactive.function.client: TRACE
    reactor.netty.http.client: DEBUG
    org:
      springframework:
        ai:
          chat:
            client:
              advisor:
                SimpleLoggerAdvisor: DEBUG