spring:
  application:
    name: helloworld
  ai:
    ollama:
      #base-url: http://localhost:11434
      base-url: http://localhost:7869
      chat:
        options:
          model: llama3
#    openai:
#      api-key: ${OPENAI_API_KEY}
#      chat:
#        options:
#          temperature: 0.7
#          #model: gpt-5
#          model: gpt-4.1-nano

server:
  port: 8081
