spring:
  application:
    name: graph-using-alibaba
  ai:
    #    ollama:
    #      base-url: http://localhost:7869
    #      chat:
    #        options:
    #          model: Qwen3
    chat:
      client:
        observations:
          log-prompt: true
          log-completion: true
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          temperature: 0.7
          #model: gpt-5
          model: gpt-4.1-nano

server:
  port: 8081

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # Set to 1.0 for local debugging
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
  metrics:
    distribution:
      percentiles-histogram:
        gen.ai.client.token.usage: true
        spring.ai.chat.client: true

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor:
                SimpleLoggerAdvisor: TRACE